# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 176306b8a67130d19eb2fc0b7c8d021a80747107d00113ad6c6f40b4f7332e9276b4dcf9334f851558a522340a841fa6e5e989c60ca7d0db5a474f339cf269d7

test:
  secret_key_base: 5a878e669a06c88653efacc760dba51ac00ae79babc820f60a55b3dd422346b0891b5398974e69af959b72319ae77045f9de23662217c637ce7c196c21d818bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
